{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhangyue.plugins",
    "module": "method-trace",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "2fhx4vmfxvetvhbleatcehla7a"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "method-trace-1.0.jar",
          "url": "method-trace-1.0.jar",
          "size": 45680,
          "sha512": "4882f1b3250653b4f4e4717d9b7cc9cf29899654963f63f7f59f1595f433e556082ae57bfc1e68ee5712b911fab5322c78ae9c53eaeaf1c39f08ccfd02fb56d2",
          "sha256": "b7ee7c48e321e9e4b02dea584896028480e2e8d4551ec1220b9caa5351825180",
          "sha1": "c3dc7ec22680592bb4fba793eebc3beb75d18408",
          "md5": "92f5c264970d155f446e8e097aead4a3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.2"
          }
        },
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "method-trace-1.0.jar",
          "url": "method-trace-1.0.jar",
          "size": 45680,
          "sha512": "4882f1b3250653b4f4e4717d9b7cc9cf29899654963f63f7f59f1595f433e556082ae57bfc1e68ee5712b911fab5322c78ae9c53eaeaf1c39f08ccfd02fb56d2",
          "sha256": "b7ee7c48e321e9e4b02dea584896028480e2e8d4551ec1220b9caa5351825180",
          "sha1": "c3dc7ec22680592bb4fba793eebc3beb75d18408",
          "md5": "92f5c264970d155f446e8e097aead4a3"
        }
      ]
    }
  ]
}
