{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhangyue.plugins",
    "module": "method-trace",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "ffiy5d4mtvddbdzgkyrfqj4rxe"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "method-trace-1.0.jar",
          "url": "method-trace-1.0.jar",
          "size": 47477,
          "sha512": "81fc6a294d44a00b057d6313e202447ff8dfc70944c5597e03e1c43a4f778c0497c0877961b5d43787824e72a835dfb00a6bf11a11a8d35685196ad9460bab8f",
          "sha256": "4c45fb5c2dd02f8a109d1d38164470a92bfbfa47f552a204a7a476536a82db29",
          "sha1": "3dd889e5b61aecaa40601febc83ff4ec78ad2882",
          "md5": "14e99f94291b031583fc989ff248ecf3"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "method-trace-1.0.jar",
          "url": "method-trace-1.0.jar",
          "size": 47477,
          "sha512": "81fc6a294d44a00b057d6313e202447ff8dfc70944c5597e03e1c43a4f778c0497c0877961b5d43787824e72a835dfb00a6bf11a11a8d35685196ad9460bab8f",
          "sha256": "4c45fb5c2dd02f8a109d1d38164470a92bfbfa47f552a204a7a476536a82db29",
          "sha1": "3dd889e5b61aecaa40601febc83ff4ec78ad2882",
          "md5": "14e99f94291b031583fc989ff248ecf3"
        }
      ]
    }
  ]
}
