{
  "formatVersion": "1.1",
  "component": {
    "group": "com.zhangyue.plugins",
    "module": "method-trace",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.2",
      "buildId": "qzdafzdwgjbvjhuoihncdrgr3m"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "method-trace-1.0.jar",
          "url": "method-trace-1.0.jar",
          "size": 46761,
          "sha512": "d5ac7b0874711eb8a275376e33a050518f01c6d558d644b8ed6c3fbd7be1cdc63ec56dbd602ab11daf97168dece11e5e4cd25c2411b00f35de8fa96f11a1b730",
          "sha256": "98d7f25cfd3573b66f8fa11c3c8ceaee7d6145a545baeab886a8247859d371d9",
          "sha1": "6cbea68b6a3741622c57e25366f76c5ba5b3bdc2",
          "md5": "6d5af68aad28ebdfda4153da5ee5d031"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.6.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "method-trace-1.0.jar",
          "url": "method-trace-1.0.jar",
          "size": 46761,
          "sha512": "d5ac7b0874711eb8a275376e33a050518f01c6d558d644b8ed6c3fbd7be1cdc63ec56dbd602ab11daf97168dece11e5e4cd25c2411b00f35de8fa96f11a1b730",
          "sha256": "98d7f25cfd3573b66f8fa11c3c8ceaee7d6145a545baeab886a8247859d371d9",
          "sha1": "6cbea68b6a3741622c57e25366f76c5ba5b3bdc2",
          "md5": "6d5af68aad28ebdfda4153da5ee5d031"
        }
      ]
    }
  ]
}
